import { createContext, useContext, useState, useCallback } from 'react';

const translations = {
  en: {
    allNews: 'All News',
    topNews: 'Top News',
    likedNews: 'Liked News',
    recentNews: 'Recent News',
    localNews: 'Local News',
    settings: 'Settings',
    admin: 'Admin',
    submitNews: 'Submit News',
    login: 'Login',
    register: 'Sign Up',
    logout: 'Logout',
    home: 'Home',
    trp: 'TRP',
    searchNews: 'Search news...',
    category: 'Category',
    sortBy: 'Sort By',
    allCategories: 'All Categories',
    technology: 'Technology',
    business: 'Business',
    sports: 'Sports',
    entertainment: 'Entertainment',
    health: 'Health',
    science: 'Science',
    world: 'World',
    politics: 'Politics',
    local: 'Local',
    newestFirst: 'Newest First',
    oldestFirst: 'Oldest First',
    mostViews: 'Most Views',
    mostLiked: 'Most Liked',
    noNewsFound: 'No news found',
    tryAdjusting: 'Try adjusting your search or filter criteria',
    latestNews: 'Latest News',
    relatedNews: 'Related News',
    views: 'Views',
    likes: 'Likes',
    comments: 'Comments',
    share: 'Share',
    readMore: 'Read More',
    advertisement: 'Advertisement',
    setLocation: 'Set Location',
    changeLocation: 'Change Location',
    cityRegion: 'City or Region',
    loginRequired: 'Login Required',
    pleaseLogin: 'Please login to view this content',
    noLikedNews: 'No liked news yet',
    startExploring: 'Start exploring and like news that interests you',
    browseNews: 'Browse News',
    enableLocation: 'Enable Location',
    enableLocationDesc: 'Set your location to discover news happening in your area',
    noLocalNews: 'No local news found',
    tryDifferentLocation: 'Try a different location or check back later',
    readFullArticle: 'Read Full Article',
    publishedOn: 'Published on',
    by: 'By',
    hot: 'HOT',
    new: 'NEW',
    filters: 'Filters',
    aboutUs: 'About Us',
    contact: 'Contact',
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',
    quickLinks: 'Quick Links',
    categories: 'Categories',
    newsletter: 'Newsletter',
    subscribeDesc: 'Subscribe to get the latest news delivered to your inbox.',
    yourEmail: 'Your email',
    subscribe: 'Subscribe',
    allRightsReserved: 'All rights reserved.',
    privacy: 'Privacy',
    terms: 'Terms',
    welcomeBack: 'Welcome Back',
    loginSubtitle: 'Login to your NewsHub account',
    email: 'Email',
    password: 'Password',
    loggingIn: 'Logging in...',
    dontHaveAccount: "Don't have an account?",
    signUp: 'Sign up',
    createAccount: 'Create Account',
    joinNewshub: 'Join NewsHub and start exploring',
    username: 'Username',
    confirmPassword: 'Confirm Password',
    passwordsDoNotMatch: 'Passwords do not match',
    passwordMinLength: 'Password must be at least 6 characters',
    creatingAccount: 'Creating Account...',
    alreadyHaveAccount: 'Already have an account?',
    submitNewsTitle: 'Submit News',
    submitNewsSubtitle: 'Share your story with the world',
    pleaseLoginToSubmit: 'Please login to submit news',
    settingsTitle: 'Settings',
    settingsSubtitle: 'Manage your profile and preferences',
    profile: 'Profile',
    preferences: 'Preferences',
    contactTab: 'Contact',
    mySubmissions: 'My Submissions',
    bio: 'Bio',
    location: 'Location',
    saveProfile: 'Save Profile',
    theme: 'Theme',
    themeDesc: 'Toggle dark/light mode from the header',
    notificationPreferences: 'Notification Preferences',
    emailNotifications: 'Email notifications',
    notifyLikes: 'Notify when someone likes your post',
    notifyComments: 'Notify when someone comments on your post',
    savePreferences: 'Save Preferences',
    contactFeedback: 'Contact & Feedback',
    feedbackDesc: "Have a question or feedback? We'd love to hear from you.",
    subject: 'Subject',
    message: 'Message',
    sendFeedback: 'Send Feedback',
    submissionsDesc: 'Track the status of your submitted articles and blog posts',
    noSubmissionsYet: 'No submissions yet',
    startSharing: 'Start sharing your stories with our readers',
    submitted: 'Submitted:',
    pending: 'pending',
    approved: 'approved',
    rejected: 'rejected',
    articleImage: 'Article Image',
    title: 'Title',
    description: 'Description',
    content: 'Content',
    submit: 'Submit',
    cancel: 'Cancel',
    successSubscribed: 'Successfully subscribed to newsletter!',
    success: 'Success!',
    clickToReadMore: 'Click to read more about this article...',
    writeComment: 'Write a comment...',
    postComment: 'Post Comment',
  },
  hi: {
    allNews: 'सभी समाचार',
    topNews: 'शीर्ष समाचार',
    likedNews: 'पसंदीदा समाचार',
    recentNews: 'हालिया समाचार',
    localNews: 'स्थानीय समाचार',
    settings: 'सेटिंग्स',
    admin: 'एडमिन',
    submitNews: 'समाचार जमा करें',
    login: 'लॉगिन',
    register: 'साइन अप',
    logout: 'लॉग आउट',
    home: 'होम',
    searchNews: 'समाचार खोजें...',
    category: 'श्रेणी',
    sortBy: 'क्रमबद्ध करें',
    allCategories: 'सभी श्रेणियां',
    technology: 'प्रौद्योगिकी',
    business: 'व्यापार',
    sports: 'खेल',
    entertainment: 'मनोरंजन',
    health: 'स्वास्थ्य',
    science: 'विज्ञान',
    world: 'विश्व',
    politics: 'राजनीति',
    local: 'स्थानीय',
    newestFirst: 'नवीनतम पहले',
    oldestFirst: 'पुराना पहले',
    mostViews: 'सबसे अधिक देखे गए',
    mostLiked: 'सबसे पसंद किए गए',
    noNewsFound: 'कोई समाचार नहीं मिला',
    tryAdjusting: 'अपनी खोज या फ़िल्टर मानदंड समायोजित करने का प्रयास करें',
    latestNews: 'ताज़ा समाचार',
    relatedNews: 'संबंधित समाचार',
    views: 'दृश्य',
    likes: 'पसंद',
    comments: 'टिप्पणियां',
    share: 'साझा करें',
    readMore: 'और पढ़ें',
    advertisement: 'विज्ञापन',
    setLocation: 'स्थान सेट करें',
    changeLocation: 'स्थान बदलें',
    cityRegion: 'शहर या क्षेत्र',
    loginRequired: 'लॉगिन आवश्यक',
    pleaseLogin: 'इस सामग्री को देखने के लिए कृपया लॉगिन करें',
    noLikedNews: 'अभी तक कोई पसंदीदा समाचार नहीं',
    startExploring: 'अन्वेषण शुरू करें और जो समाचार आपको रुचिकर लगे उन्हें पसंद करें',
    browseNews: 'समाचार ब्राउज़ करें',
    enableLocation: 'स्थान सक्षम करें',
    enableLocationDesc: 'अपने क्षेत्र में होने वाली खबरों की खोज के लिए अपना स्थान सेट करें',
    noLocalNews: 'कोई स्थानीय समाचार नहीं मिला',
    tryDifferentLocation: 'किसी अन्य स्थान का प्रयास करें या बाद में पुनः जांचें',
    readFullArticle: 'पूरा लेख पढ़ें',
    publishedOn: 'प्रकाशित',
    by: 'द्वारा',
    hot: 'हॉट',
    new: 'नया',
    filters: 'फ़िल्टर',
    aboutUs: 'हमारे बारे में',
    contact: 'संपर्क करें',
    privacyPolicy: 'गोपनीयता नीति',
    termsOfService: 'सेवा की शर्तें',
    quickLinks: 'त्वरित लिंक',
    categories: 'श्रेणियां',
    newsletter: 'न्यूज़लेटर',
    subscribeDesc: 'नवीनतम समाचार अपने इनबॉक्स में प्राप्त करने के लिए सदस्यता लें।',
    yourEmail: 'आपका ईमेल',
    subscribe: 'सदस्यता लें',
    allRightsReserved: 'सर्वाधिकार सुरक्षित।',
    privacy: 'गोपनीयता',
    terms: 'शर्तें',
    welcomeBack: 'वापसी पर स्वागत है',
    loginSubtitle: 'अपने NewsHub खाते में लॉगिन करें',
    email: 'ईमेल',
    password: 'पासवर्ड',
    loggingIn: 'लॉगिन हो रहा है...',
    dontHaveAccount: 'खाता नहीं है?',
    signUp: 'साइन अप करें',
    createAccount: 'खाता बनाएं',
    joinNewshub: 'NewsHub से जुड़ें और अन्वेषण शुरू करें',
    username: 'उपयोगकर्ता नाम',
    confirmPassword: 'पासवर्ड की पुष्टि करें',
    passwordsDoNotMatch: 'पासवर्ड मेल नहीं खाते',
    passwordMinLength: 'पासवर्ड कम से कम 6 अक्षर का होना चाहिए',
    creatingAccount: 'खाता बनाया जा रहा है...',
    alreadyHaveAccount: 'पहले से खाता है?',
    submitNewsTitle: 'समाचार जमा करें',
    submitNewsSubtitle: 'दुनिया के साथ अपनी कहानी साझा करें',
    pleaseLoginToSubmit: 'समाचार जमा करने के लिए कृपया लॉगिन करें',
    settingsTitle: 'सेटिंग्स',
    settingsSubtitle: 'अपनी प्रोफ़ाइल और प्राथमिकताएं प्रबंधित करें',
    profile: 'प्रोफ़ाइल',
    preferences: 'प्राथमिकताएं',
    contactTab: 'संपर्क',
    mySubmissions: 'मेरी सबमिशन',
    bio: 'बायो',
    location: 'स्थान',
    saveProfile: 'प्रोफ़ाइल सहेजें',
    theme: 'थीम',
    themeDesc: 'हेडर से डार्क/लाइट मोड टॉगल करें',
    notificationPreferences: 'सूचना प्राथमिकताएं',
    emailNotifications: 'ईमेल सूचनाएं',
    notifyLikes: 'जब कोई आपकी पोस्ट को पसंद करे तो सूचित करें',
    notifyComments: 'जब कोई आपकी पोस्ट पर टिप्पणी करे तो सूचित करें',
    savePreferences: 'प्राथमिकताएं सहेजें',
    contactFeedback: 'संपर्क और प्रतिक्रिया',
    feedbackDesc: 'कोई प्रश्न या प्रतिक्रिया है? हम आपसे सुनना पसंद करेंगे।',
    subject: 'विषय',
    message: 'संदेश',
    sendFeedback: 'प्रतिक्रिया भेजें',
    submissionsDesc: 'अपने प्रस्तुत लेखों और ब्लॉग पोस्ट की स्थिति ट्रैक करें',
    noSubmissionsYet: 'अभी तक कोई सबमिशन नहीं',
    startSharing: 'हमारे पाठकों के साथ अपनी कहानियां साझा करना शुरू करें',
    submitted: 'जमा किया:',
    pending: 'लंबित',
    approved: 'स्वीकृत',
    rejected: 'अस्वीकृत',
    articleImage: 'लेख छवि',
    title: 'शीर्षक',
    description: 'विवरण',
    content: 'सामग्री',
    submit: 'जमा करें',
    cancel: 'रद्द करें',
    successSubscribed: 'न्यूज़लेटर की सदस्यता सफलतापूर्वक ली गई!',
    success: 'सफल!',
    clickToReadMore: 'इस लेख के बारे में और पढ़ने के लिए क्लिक करें...',
    writeComment: 'टिप्पणी लिखें...',
    postComment: 'टिप्पणी पोस्ट करें',
  },
};

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('language') || 'en';
  });

  const toggleLanguage = useCallback(() => {
    setLanguage((prev) => {
      const newLang = prev === 'en' ? 'hi' : 'en';
      localStorage.setItem('language', newLang);
      return newLang;
    });
  }, []);

  const t = useCallback((key) => {
    return translations[language]?.[key] || translations.en[key] || key;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};